### ISSUE TITLE
I2C not defined

### ISSUE THREAD

**Issue by PeteDouma** [adafruit/Adafruit_CircuitPython_PCT2075#21]
I am running the sample code on Raspberry Pi Zero W, with Rasparian Stretch and python3.5  I keep getting thisl

File "pct.py", line 3, in <module>
    import adafruit_pct2075
  File "/home/lib/python3.5/site-packages/adafruit_pct2075.py", line 38, in <module>
    import adafruit_bus_device.i2c_device as i2cdevice
  File "/home/lib/python3.5/site-packages/adafruit_bus_device/i2c_device.py", line 25, in <module>
    class I2CDevice:
  File "/home/lib/python3.5/site-packages/adafruit_bus_device/i2c_device.py", line 55, in I2CDevice
    def __init__(self, i2c: I2C, device_address: int, probe: bool = True) -> None:
NameError: name 'I2C' is not defined

**Comment by ladyada** [comment]
@tekktrik hiya this is a typing thing i think :)

**Comment by tekktrik** [comment]
Hey @PeteDouma!  You're using Python 3.5, but Blinka currently supports Python 3.7 as the minimum version.  You'll want to update your version of Python to 3.7 using [this guide](https://raspberrytips.com/install-latest-python-raspberry-pi/) in order to use this library (and other CircuitPython libraries as well) on the Raspberry Pi.

**Comment by ladyada** [comment]
@tekktrik does blinka have a version min requirement that it can complain about :)

**Comment by tekktrik** [comment]
It looks like it's defined appropriately in Blinka:

https://github.com/adafruit/Adafruit_Blinka/blob/ac9c311d6e3b7419c891f8c116c63503724385c5/setup.py#L52

But it looks like `adafruit_bus_device` should require the correct Blinka version of min 7.0.0.  I can PR the library to add it to its `setup.py`.

**Comment by tekktrik** [comment]
Wait, my fork was out of date, the current version of `adafruit_bus_device` does require min Python 3.7:

https://github.com/tekktrik/Adafruit_CircuitPython_BusDevice/blob/9addf6a26fef3a32c78d574c66452b6210eca5c5/setup.py#L37

This issue of failing to find `I2C` in `adafruit_bus_device` is actually how the minimum version issue was discovered, so that's how I recognized it :sweat_smile:

**Comment by tekktrik** [comment]
Is it worth removing bad versions of `adafruit_bus_device` from PyPI?  If I understand correctly, because those are still listed, `pip` will find the faulty version eventually and this error will keep occurring given how widely used it is.  Disabling those releases in between (I think) will at least stop that.

**Comment by ladyada** [comment]
nope, for regression testing we always keep old versions, we should just try to get people to upgrade

**Comment by tekktrik** [comment]
Sounds good!  @PeteDouma let me know if you need any help, the guide I linked is what I used to upgrade my own Raspberry Pi Zero 2 W so it should have everything you need!

**Comment by PeteDouma** [comment]
Thanks for this. We were running devices on Raspberry Pi Stretch, which only has python 3.5. The devices are in the field but  I was able to get it to work with an earlier version. Thank you all for great support.
